// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAL5PyFuigAmP0L-Pql-ht6MYQcYn_fYZM',
    appId: '1:431613961853:android:7199e8c492e05f57bbb314',
    messagingSenderId: '431613961853',
    projectId: 'notes-manager-80e80',
    storageBucket: 'notes-manager-80e80.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_FO_LoXASHOyDya80SO3Ug0BI39a19Jw',
    appId: '1:431613961853:ios:a7099365c06a25bdbbb314',
    messagingSenderId: '431613961853',
    projectId: 'notes-manager-80e80',
    storageBucket: 'notes-manager-80e80.firebasestorage.app',
    iosBundleId: 'com.example.notesManager',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTe8S7aiQz_6nqptGSJZkFCgTb1DoqpMo',
    appId: '1:431613961853:web:0091c9357e993e6dbbb314',
    messagingSenderId: '431613961853',
    projectId: 'notes-manager-80e80',
    authDomain: 'notes-manager-80e80.firebaseapp.com',
    storageBucket: 'notes-manager-80e80.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_FO_LoXASHOyDya80SO3Ug0BI39a19Jw',
    appId: '1:431613961853:ios:a7099365c06a25bdbbb314',
    messagingSenderId: '431613961853',
    projectId: 'notes-manager-80e80',
    storageBucket: 'notes-manager-80e80.firebasestorage.app',
    iosBundleId: 'com.example.notesManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTe8S7aiQz_6nqptGSJZkFCgTb1DoqpMo',
    appId: '1:431613961853:web:baa35358dc3853d7bbb314',
    messagingSenderId: '431613961853',
    projectId: 'notes-manager-80e80',
    authDomain: 'notes-manager-80e80.firebaseapp.com',
    storageBucket: 'notes-manager-80e80.firebasestorage.app',
  );
}
